/* Generated by Yosys 0.27+12 (git sha1 dc0a799c0, gcc 11.3.0-1ubuntu1~22.04 -fPIC -Os) */

(* cells_not_processed =  1  *)
(* src = "mul.v:1.1-3.10" *)
module top(op0, op1, result);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  (* src = "mul.v:1.24-1.27" *)
  input [2:0] op0;
  wire [2:0] op0;
  (* src = "mul.v:1.41-1.44" *)
  input [2:0] op1;
  wire [2:0] op1;
  (* src = "mul.v:1.59-1.65" *)
  output [5:0] result;
  wire [5:0] result;
  sky130_fd_sc_hd__and2_0 _16_ (
    .A(op1[0]),
    .B(op0[0]),
    .X(result[0])
  );
  sky130_fd_sc_hd__nand2_1 _17_ (
    .A(op0[1]),
    .B(op1[1]),
    .Y(_00_)
  );
  sky130_fd_sc_hd__nand3_1 _18_ (
    .A(op0[1]),
    .B(op1[1]),
    .C(result[0]),
    .Y(_01_)
  );
  sky130_fd_sc_hd__a22oi_1 _19_ (
    .A1(op0[1]),
    .A2(op1[0]),
    .B1(op0[0]),
    .B2(op1[1]),
    .Y(_02_)
  );
  sky130_fd_sc_hd__a31oi_1 _20_ (
    .A1(op0[1]),
    .A2(op1[1]),
    .A3(result[0]),
    .B1(_02_),
    .Y(result[1])
  );
  sky130_fd_sc_hd__nand2_1 _21_ (
    .A(op0[2]),
    .B(op1[1]),
    .Y(_03_)
  );
  sky130_fd_sc_hd__nand4_1 _22_ (
    .A(op0[1]),
    .B(op1[0]),
    .C(op0[2]),
    .D(op1[1]),
    .Y(_04_)
  );
  sky130_fd_sc_hd__a22o_1 _23_ (
    .A1(op1[0]),
    .A2(op0[2]),
    .B1(op1[1]),
    .B2(op0[1]),
    .X(_05_)
  );
  sky130_fd_sc_hd__and4_1 _24_ (
    .A(op1[2]),
    .B(op0[0]),
    .C(_04_),
    .D(_05_),
    .X(_06_)
  );
  sky130_fd_sc_hd__a22oi_1 _25_ (
    .A1(op1[2]),
    .A2(op0[0]),
    .B1(_04_),
    .B2(_05_),
    .Y(_07_)
  );
  sky130_fd_sc_hd__or3_1 _26_ (
    .A(_01_),
    .B(_06_),
    .C(_07_),
    .X(_08_)
  );
  sky130_fd_sc_hd__o21ai_0 _27_ (
    .A1(_06_),
    .A2(_07_),
    .B1(_01_),
    .Y(_09_)
  );
  sky130_fd_sc_hd__and2_0 _28_ (
    .A(_08_),
    .B(_09_),
    .X(result[2])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _29_ (
    .A(_04_),
    .SLEEP(_06_),
    .X(_10_)
  );
  sky130_fd_sc_hd__nand2_1 _30_ (
    .A(op0[1]),
    .B(op1[2]),
    .Y(_11_)
  );
  sky130_fd_sc_hd__xnor2_1 _31_ (
    .A(_03_),
    .B(_11_),
    .Y(_12_)
  );
  sky130_fd_sc_hd__xor2_1 _32_ (
    .A(_10_),
    .B(_12_),
    .X(_13_)
  );
  sky130_fd_sc_hd__xnor2_1 _33_ (
    .A(_08_),
    .B(_13_),
    .Y(result[3])
  );
  sky130_fd_sc_hd__nand3_1 _34_ (
    .A(op0[2]),
    .B(op1[2]),
    .C(_00_),
    .Y(_14_)
  );
  sky130_fd_sc_hd__maj3_1 _35_ (
    .A(_08_),
    .B(_10_),
    .C(_12_),
    .X(_15_)
  );
  sky130_fd_sc_hd__xor2_1 _36_ (
    .A(_14_),
    .B(_15_),
    .X(result[4])
  );
  sky130_fd_sc_hd__o22ai_1 _37_ (
    .A1(_03_),
    .A2(_11_),
    .B1(_14_),
    .B2(_15_),
    .Y(result[5])
  );
endmodule
